"""add field currency in person table

Revision ID: 7dda082c1b2c
Revises: 7a4e23edb857
Create Date: 2023-01-06 10:39:28.074148

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7dda082c1b2c'
down_revision = '7a4e23edb857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('currenty', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'currenty')
    # ### end Alembic commands ###
