"""fix field currency in person table

Revision ID: 7fcc45026f4d
Revises: 7dda082c1b2c
Create Date: 2023-01-06 13:39:20.716332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7fcc45026f4d'
down_revision = '7dda082c1b2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column(
        'currency',
        sqlmodel.sql.sqltypes.AutoString(),
        nullable=True))
    op.drop_column('person', 'currenty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('currenty', sa.VARCHAR(), nullable=True))
    op.drop_column('person', 'currency')
    # ### end Alembic commands ###
